version: '3.8'
services:
  movies:
    image: gurendra/mmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: gurendra/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: gurendra/dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: gurendra/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
